// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO2wR7VmG72nqqu-kDj8Nt3USI22a890Q',
    appId: '1:580426483615:web:55feaa1f816c3965969faa',
    messagingSenderId: '580426483615',
    projectId: 'labor-f4ef8',
    authDomain: 'labor-f4ef8.firebaseapp.com',
    storageBucket: 'labor-f4ef8.appspot.com',
    measurementId: 'G-EBN2C301DW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1UCrCtIvoY6u4zE9WEIsQhRfYnAygywU',
    appId: '1:580426483615:android:a79674393c63a3e5969faa',
    messagingSenderId: '580426483615',
    projectId: 'labor-f4ef8',
    storageBucket: 'labor-f4ef8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcZDITd-L0NTo65Ro0DTQWfYbkg_Jesf0',
    appId: '1:580426483615:ios:6cd0c6fe19baa8a2969faa',
    messagingSenderId: '580426483615',
    projectId: 'labor-f4ef8',
    storageBucket: 'labor-f4ef8.appspot.com',
    iosClientId: '580426483615-nthp3mcafcacqf18os0l0f9095naab9c.apps.googleusercontent.com',
    iosBundleId: 'com.example.laborApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcZDITd-L0NTo65Ro0DTQWfYbkg_Jesf0',
    appId: '1:580426483615:ios:6cd0c6fe19baa8a2969faa',
    messagingSenderId: '580426483615',
    projectId: 'labor-f4ef8',
    storageBucket: 'labor-f4ef8.appspot.com',
    iosClientId: '580426483615-nthp3mcafcacqf18os0l0f9095naab9c.apps.googleusercontent.com',
    iosBundleId: 'com.example.laborApplication',
  );
}
